
#████████████████████████████████████████████████████████████████████████████████████████
#█░░░░░░░░░░░░░░█░░░░░░██░░░░░░█░░░░░░██████████░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░██░░░░░░░░█
#█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀░░░░░░░░░░██░░▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀░░██░░▄▀▄▀░░█
#█░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░██░░▄▀░░█░░░░░░▄▀░░░░░░█░░░░▄▀░░██░░▄▀░░░░█
#█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░░░░░▄▀░░██░░▄▀░░█████░░▄▀░░███████░░▄▀▄▀░░▄▀▄▀░░███
#█░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░██░░▄▀░░█████░░▄▀░░███████░░░░▄▀▄▀▄▀░░░░███
#█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░██░░▄▀░░█████░░▄▀░░█████████░░░░▄▀░░░░█████
#█░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░██░░▄▀░░█████░░▄▀░░███████████░░▄▀░░███████
#█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░░░░░▄▀░░█████░░▄▀░░███████████░░▄▀░░███████
#█░░▄▀░░█████████░░▄▀░░░░░░▄▀░░█░░▄▀░░██░░▄▀▄▀▄▀▄▀▄▀░░█████░░▄▀░░███████████░░▄▀░░███████
#█░░▄▀░░█████████░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██░░░░░░░░░░▄▀░░█████░░▄▀░░███████████░░▄▀░░███████
#█░░░░░░█████████░░░░░░░░░░░░░░█░░░░░░██████████░░░░░░█████░░░░░░███████████░░░░░░███████
#████████████████████████████████████████████████████████████████████████████████████████

Settings:

  #The character that shows the plugin that there is a color code. [DEFAULT: &]
  ColorCodeCharacter: '&'

  #Schould colorcodes be enabled in chat? [true/false]
  InChat: 'true'
  #what permissions need the Player to use this? leave blank if no permissions should be required.
  PermissionsChat: ''

  #Schould colorcodes be enabled at signs? [true/false]
  AtSigns: 'true'
  #what permissions need the Player to use this? leave blank if no permissions should be required.
  PermissionsSign: ''

Messages:
  #The message that will show if a player has no permissions for something. [You can use colors with "&"]
  NoPerms: '&7[&6ColorCodes&7] &cYou don´t have permissions to do this!'